In [1]:
#Q1 Write a Python program to convert an array to an ordinary list with the same items

import numpy as np

# 1d array to list
arr = np.array([1, 2, 3])
print(f'NumPy Array:\n{arr}')

list1 = arr.tolist()
print(f'List: {list1}')

NumPy Array:
[1 2 3]
List: [1, 2, 3]


In [2]:
#Q2 Write a NumPy program to compute the sum of the diagonal elements of a given array.

arr= np.arange(16)
arr= np.reshape(arr,(4,4))

a=np.diagonal(arr, 0,0,1)

result=sum(a)
print(result)




30


In [3]:
#Q3 Given an array of your choice, get all the values higher than X

import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


In [5]:
#Q4 Given two arrays, A & B have the same shape. 
import numpy as np
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
C= a + b
print(C)

[5 6 7]


In [6]:
#Q5  Write a NumPy program to subtract the mean of each row of a given matrix.

import numpy as np
a = np.random.rand(3, 4)
print(a)
b = a - a.mean(axis=1, keepdims=True)
print(b)





[[0.31448564 0.44078298 0.03741876 0.79174273]
 [0.96376978 0.70206319 0.69458194 0.02432434]
 [0.34179675 0.08199044 0.64275879 0.90834633]]
[[-0.08162189  0.04467545 -0.35868877  0.3956352 ]
 [ 0.36758497  0.10587838  0.09839713 -0.57186047]
 [-0.15192633 -0.41173264  0.14903571  0.41462325]]
